import React, { useState } from 'react';
import { TrendingUp, Sparkles, Plus, X } from 'lucide-react';
import { Button } from './Button';
import type { SuggestedTopic } from '../../lib/agent-types';

interface TopicSelectorProps {
  suggestedTopics: SuggestedTopic[];
  /** Deterministic prompts from role + skills (not LLM). Shown without “AI” branding. */
  heuristicTopicStrings?: string[];
  selectedTopics: string[];
  onChange: (topics: string[]) => void;
  minRequired?: number;
  /** Copy for the dashed empty state when there are no suggestion pills */
  emptySuggestionsMessage?: string;
}

export const TopicSelector: React.FC<TopicSelectorProps> = ({
  suggestedTopics,
  heuristicTopicStrings = [],
  selectedTopics,
  onChange,
  minRequired = 1,
  emptySuggestionsMessage,
}) => {
  const [customTopic, setCustomTopic] = useState('');

  const toggleTopic = (topic: string) => {
    if (selectedTopics.includes(topic)) {
      onChange(selectedTopics.filter(t => t !== topic));
    } else {
      onChange([...selectedTopics, topic]);
    }
  };

  const addCustomTopic = () => {
    const trimmed = customTopic.trim();
    if (trimmed && !selectedTopics.includes(trimmed)) {
      onChange([...selectedTopics, trimmed]);
      setCustomTopic('');
    }
  };

  const trendingTopics = suggestedTopics
    .filter(t => t.trending)
    .sort((a, b) => b.relevance_score - a.relevance_score);

  const aiSuggestedTopics = suggestedTopics
    .filter(t => !t.trending)
    .sort((a, b) => b.relevance_score - a.relevance_score);

  const suggestedNames = suggestedTopics.map(t => t.topic);
  const heuristicSet = new Set(heuristicTopicStrings);
  const customSelected = selectedTopics.filter(
    t => !suggestedNames.includes(t) && !heuristicSet.has(t)
  );

  const renderTopicPill = ({ topic }: SuggestedTopic, icon: React.ReactNode) => (
    <button
      key={topic}
      type="button"
      onClick={() => toggleTopic(topic)}
      className={`px-4 py-2 rounded-full border text-sm font-medium transition-all inline-flex items-center gap-1.5 ${
        selectedTopics.includes(topic)
          ? 'border-indigo-600 bg-indigo-600 text-white shadow-md'
          : 'border-gray-200 bg-white text-gray-600 hover:border-indigo-300'
      }`}
    >
      {icon}
      {topic}
    </button>
  );

  const showHeuristic = heuristicTopicStrings.length > 0;

  return (
    <div className="space-y-5">
      {showHeuristic && (
        <div className="space-y-2">
          <div className="flex items-center gap-1.5">
            <TrendingUp className="w-4 h-4 text-emerald-600" />
            <p className="text-sm font-bold text-gray-700">Suggested from your role & skills</p>
            <span className="text-xs text-emerald-700 font-medium bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-100">
              Quick prompts — edit anytime
            </span>
          </div>
          <p className="text-xs text-gray-500">
            Built from your designation and skills (not generated by an AI model).
          </p>
          <div className="flex flex-wrap gap-2">
            {heuristicTopicStrings.map(topic =>
              renderTopicPill(
                { topic, relevance_score: 0, trending: false, category: 'career', reasoning: '' },
                <TrendingUp className={`w-3.5 h-3.5 ${selectedTopics.includes(topic) ? 'text-white' : 'text-emerald-600'}`} />
              )
            )}
          </div>
        </div>
      )}

      {suggestedTopics.length > 0 ? (
        <>
          {/* Trending Topics */}
          {trendingTopics.length > 0 && (
            <div className="space-y-2">
              <div className="flex items-center gap-1.5">
                <TrendingUp className="w-4 h-4 text-orange-500" />
                <p className="text-sm font-bold text-gray-700">Trending Now</p>
                <span className="text-xs text-orange-500 font-medium bg-orange-50 px-2 py-0.5 rounded-full border border-orange-100">
                  Latest industry trends
                </span>
              </div>
              <div className="flex flex-wrap gap-2">
                {trendingTopics.map(t =>
                  renderTopicPill(t, (
                    <TrendingUp className={`w-3.5 h-3.5 ${selectedTopics.includes(t.topic) ? 'text-white' : 'text-orange-500'}`} />
                  ))
                )}
              </div>
            </div>
          )}

          {/* AI-Suggested Topics */}
          {aiSuggestedTopics.length > 0 && (
            <div className="space-y-2">
              <div className="flex items-center gap-1.5">
                <Sparkles className="w-4 h-4 text-indigo-500" />
                <p className="text-sm font-bold text-gray-700">AI-Suggested for You</p>
                <span className="text-xs text-indigo-600 font-medium bg-indigo-50 px-2 py-0.5 rounded-full border border-indigo-100">
                  Based on your resume
                </span>
              </div>
              <div className="flex flex-wrap gap-2">
                {aiSuggestedTopics.map(t =>
                  renderTopicPill(t, (
                    <Sparkles className={`w-3.5 h-3.5 ${selectedTopics.includes(t.topic) ? 'text-white' : 'text-indigo-400'}`} />
                  ))
                )}
              </div>
            </div>
          )}
        </>
      ) : !showHeuristic ? (
        <div className="p-6 border-2 border-dashed border-gray-200 rounded-xl text-center text-gray-500">
          <p className="text-sm">
            {emptySuggestionsMessage ?? 'Upload your resume to get topic suggestions, or add topics manually below.'}
          </p>
        </div>
      ) : null}

      {/* Add Custom Topic */}
      <div className="pt-4 border-t border-gray-100">
        <label className="block text-sm font-bold text-gray-700 mb-2">Add Custom Topic</label>
        <div className="flex gap-2">
          <input
            type="text"
            value={customTopic}
            onChange={(e) => setCustomTopic(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addCustomTopic())}
            placeholder="e.g. Remote Work Culture"
            className="flex-1 px-4 py-2 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none text-sm"
          />
          <Button variant="secondary" onClick={addCustomTopic} disabled={!customTopic.trim()} type="button">
            <Plus className="w-4 h-4 mr-1" /> Add
          </Button>
        </div>
      </div>

      {/* Selected Pills */}
      {selectedTopics.length > 0 && (
        <div>
          <p className="text-xs font-bold text-gray-400 uppercase mb-2">
            Selected for Automation ({selectedTopics.length}):
          </p>
          <div className="flex flex-wrap gap-2">
            {selectedTopics.map(t => (
              <div
                key={t}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold border ${
                  customSelected.includes(t)
                    ? 'bg-purple-50 text-purple-700 border-purple-100'
                    : heuristicSet.has(t)
                      ? 'bg-emerald-50 text-emerald-800 border-emerald-100'
                      : 'bg-green-50 text-green-700 border-green-100'
                }`}
              >
                {t}
                <button type="button" onClick={() => toggleTopic(t)} className="hover:text-red-500">
                  <X className="w-3 h-3" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {minRequired > 0 && selectedTopics.length < minRequired && (
        <p className="text-xs text-gray-400">Select at least {minRequired} topic to continue</p>
      )}
    </div>
  );
};
